import type { Metadata, Viewport } from "next";
import { Montserrat } from "next/font/google";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/core/sidebar";
import Header from "@/components/core/header";
import Footer from "@/components/core/footer";
import NextTopLoader from "nextjs-toploader";
import { ThemeProvider } from "@/lib/theme-provider";
import PageWrapper from "@/components/core/page-wrapper";
import { Toaster } from "@/components/ui/toaster";

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dentist app",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen", montserrat.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader color="#1c84ee" showSpinner={false} />
          <main className="flex h-full relative bg-gray/50 dark:bg-dark-3">
            <Sidebar />
            <PageWrapper>
              <Header />
              {children}
              <Footer />
            </PageWrapper>
          </main>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
